### PR TITLE
Clean up children

### PR DESCRIPTION
**Pull request by wasade**
This will automatically clean up children in the case of redis key expiration, also adds tests for traverse

### CODE REVIEW

**Comment by antgonza** [comment]
:+1:

**Comment by wasade** [comment]
@ElDeveloper, can you look at this? This will resolve that issue we found where the keys were expiring by implicitly cleaning up "dead" children

**Comment by ElDeveloper** [comment]
I won't be able to have a look any time soon, I suggest that someone else review this.

Yoshiki Vázquez-Baeza

**Comment by wasade** [comment]
@josenavas @squirrelo @adamrp, either of you able to give a :+1:?

**Pull request merged**
