### PR TITLE
optional div

### LINKED ISSUE #17: moi_list.init should have a parameter to specify the destination in the DOM
As part of `moi_list`'s initialization, the object is appended to the body of the current document. I think it would be better to allow an extra argument to be passed, this argument would indicate the id of the element where the list should be appended to, for example:

```javascript
this.init = function (group_id, destination) {
// initialization code
}

// usage
moi_list.init('xxxxxxxxxxx', 'updates-div');
```

### PR DESCRIPTION
**Pull request by wasade**
Fixes #17

### CODE REVIEW

**Comment by josenavas** [comment]
@ElDeveloper can you review this PR (should be quick). The impression that I had from the issue is that the the list will be appended to the passed div, but it looks like it is still appended to the body of the document. Is that correct or I'm misunderstanding something?

**Comment by ElDeveloper** [comment]
@josenavas You are right, the moi_list object should be appended to whatever element is being passed in the div argument. Re-reading my comment in #17, I now realize that I completely misunderstood @wasade here:
https://github.com/biocore/mustached-octo-ironman/issues/17#issuecomment-107744136


... sorry :L

**Comment by wasade** [comment]
No worries, how's that last commit look?

**Comment by ElDeveloper** [comment]
:+1:

**Comment by josenavas** [comment]
:+1:

**Comment by wasade** [comment]
le merge?

**Pull request merged**
